// JavaScript Document
new Vue({
    el: '#sample',

	data:	{
		/* side panel/menu items */
		menu1: '<a class="menuitem" href="rooms.html"> See available rooms </a><div class="divider"></div>',
		menu2: '<a class="menuitem" href="ref.html"> Book a hotel </a><div class="divider"></div>',
		menu3: '<a class="menuitem" href="ref.html"> Remove a booking request </a><div class="divider"></div>',
		menu4: '<a class="menuitem" href="ref.html"> View booking requests </a><div class="divider"></div>',
		menu5: '<a class="menuitem" href="ref.html"> Update booking requests</a>',
		/* sample data */
		name: 'Hustino',
		updates: 'update thissz',
		showName: true,
		foods:	[
			{	foodname: "apple", rating: 10},
			{	foodname: "orange", rating: 5},
			{	foodname: "choco", rating: 8},
			{	foodname: "mango", rating: 7},
		],
		ctr: 1,
		/* sample json items */
		rooms:	[
		{	Room_Name: 'Sogooood Group Study lounge',
			address: 'Makatieh',
			max_guests:	6,
			no_bedrooms:	3,
			no_bed:	2,
			no_bath:	1,
			price:	12000,
			currency:	'Php',
			currency_symbol:	'P ',
			comments_and_feedback:	'had fun. venue was conducive for murder and serial eating',
			begindate:null,
			enddate:null,
			guestnumbers:null,
		},
		{	Room_Name: 'Vicky Cart',
			address: 'Bwinja',
			max_guests:	2,
			no_bedrooms:	1,
			no_bed:	1,
			no_bath:	1,
			price:	5000,
			currency:	'Php',
			currency_symbol:	'P ',
			comments_and_feedback:	'had fun. venue was conducive for murder and serial eating',
			begindate:null,
			enddate:null,
			guestnumbers:null,
		},
		{	Room_Name: 'Sogooood Group Study lounge',
			address: 'Makatieh',
			max_guests:	6,
			no_bedrooms:	3,
			no_bed:	2,
			no_bath:	1,
			price:	12000,
			currency:	'Php',
			currency_symbol:	'P ',
			comments_and_feedback:	'had fun. venue was conducive for murder and serial eating',
			begindate:null,
			enddate:null,
			guestnumbers:null,
		},
		{	Room_Name: 'Vicky Cart',
			address: 'Bwinja',
			max_guests:	2,
			no_bedrooms:	1,
			no_bed:	1,
			no_bath:	1,
			price:	5000,
			currency:	'Php',
			currency_symbol:	'P ',
			comments_and_feedback:	'had fun. venue was conducive for murder and serial eating',
			begindate:null,
			enddate:null,
			guestnumbers:null,
		},
		{	Room_Name: 'Sogooood Group Study lounge',
			address: 'Makatieh',
			max_guests:	6,
			no_bedrooms:	3,
			no_bed:	2,
			no_bath:	1,
			price:	12000,
			currency:	'Php',
			currency_symbol:	'P ',
			comments_and_feedback:	'had fun. venue was conducive for murder and serial eating',
			begindate:null,
			enddate:null,
			guestnumbers:null,
		},
		{	Room_Name: 'Vicky Cart',
			address: 'Bwinja',
			max_guests:	2,
			no_bedrooms:	1,
			no_bed:	1,
			no_bath:	1,
			price:	5000,
			currency:	'Php',
			currency_symbol:	'P ',
			comments_and_feedback:	'had fun. venue was conducive for murder and serial eating',
			begindate:null,
			enddate:null,
			guestnumbers:null,
		},
		]
		
	},
	
	methods: {
		clearThis: function(){
			this.name=this.updates;
			this.updates="";
			this.ctr++;
		},
		setHustino: function(){
			this.name="Hustino";
			xx = 'huwaw';
			this.updates=xx;
		},
	},
});
