// JavaScript Document
new Vue({
    el: '.rooms',

	data:	{
		/* sample json items */
		rooms:	[
		{	Room_Name: 'de Finibus Bonorum et Malorum',
			address: 'Caliphornia',
			max_guests:	Math.floor((Math.random() * 10) + 1),
			no_bedrooms:	Math.floor((Math.random() * 3) + 1),
			no_bed:	Math.floor((Math.random() * 5) + 1),
			no_bath:	Math.floor((Math.random() * 5) + 1),
			price:	(Math.floor((Math.random() * 10000) + 1000)),
			currency:	'USD',
			currency_symbol:	'$ ',
			comments_and_feedback:	'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			begindate: Math.floor((Math.random() * 10) + 1),
			enddate: Math.floor((Math.random() * 10) + 10),
			guestnumbers: null,
			days_of_stay: (this.enddate - this.begindate),
		},
		{	Room_Name: 'de Finibus Bonorum et Malorum',
			address: 'Caliphornia',
			max_guests:	Math.floor((Math.random() * 10) + 1),
			no_bedrooms:	Math.floor((Math.random() * 3) + 1),
			no_bed:	Math.floor((Math.random() * 5) + 1),
			no_bath:	Math.floor((Math.random() * 5) + 1),
			price:	(Math.floor((Math.random() * 10000))),
			currency:	'USD',
			currency_symbol:	'$ ',
			comments_and_feedback:	'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			begindate: 5,
			enddate: 8,
			guestnumbers:null,
			days_of_stay: (this.enddate - this.begindate),
			currentdate: null,
		},
		{	Room_Name: 'de Finibus Bonorum et Malorum',
			address: 'Caliphornia',
			max_guests:	Math.floor((Math.random() * 10) + 1),
			no_bedrooms:	Math.floor((Math.random() * 3) + 1),
			no_bed:	Math.floor((Math.random() * 5) + 1),
			no_bath:	Math.floor((Math.random() * 5) + 1),
			price:	(Math.floor((Math.random() * 10000) + 1000)),
			currency:	'USD',
			currency_symbol:	'$ ',
			comments_and_feedback:	'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			begindate: Math.floor((Math.random() * 10) + 1),
			enddate: Math.floor((Math.random() * 10) + 10),
			guestnumbers: null,
			days_of_stay: (this.enddate - this.begindate),
		},
		{	Room_Name: 'de Finibus Bonorum et Malorum',
			address: 'Caliphornia',
			max_guests:	Math.floor((Math.random() * 10) + 1),
			no_bedrooms:	Math.floor((Math.random() * 3) + 1),
			no_bed:	Math.floor((Math.random() * 5) + 1),
			no_bath:	Math.floor((Math.random() * 5) + 1),
			price:	(Math.floor((Math.random() * 10000))),
			currency:	'USD',
			currency_symbol:	'$ ',
			comments_and_feedback:	'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			begindate: 5,
			enddate: 8,
			guestnumbers:null,
			days_of_stay: (this.enddate - this.begindate),
			currentdate: null,
		},
		{	Room_Name: 'de Finibus Bonorum et Malorum',
			address: 'Caliphornia',
			max_guests:	Math.floor((Math.random() * 10) + 1),
			no_bedrooms:	Math.floor((Math.random() * 3) + 1),
			no_bed:	Math.floor((Math.random() * 5) + 1),
			no_bath:	Math.floor((Math.random() * 5) + 1),
			price:	(Math.floor((Math.random() * 10000) + 1000)),
			currency:	'USD',
			currency_symbol:	'$ ',
			comments_and_feedback:	'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			begindate: Math.floor((Math.random() * 10) + 1),
			enddate: Math.floor((Math.random() * 10) + 10),
			guestnumbers: null,
			days_of_stay: (this.enddate - this.begindate),
		},
		{	Room_Name: 'de Finibus Bonorum et Malorum',
			address: 'Caliphornia',
			max_guests:	Math.floor((Math.random() * 10) + 1),
			no_bedrooms:	Math.floor((Math.random() * 3) + 1),
			no_bed:	Math.floor((Math.random() * 5) + 1),
			no_bath:	Math.floor((Math.random() * 5) + 1),
			price:	(Math.floor((Math.random() * 10000))),
			currency:	'USD',
			currency_symbol:	'$ ',
			comments_and_feedback:	'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			begindate: 5,
			enddate: 8,
			guestnumbers:null,
			days_of_stay: (this.enddate - this.begindate),
			currentdate: null,
		},
		{	Room_Name: 'de Finibus Bonorum et Malorum',
			address: 'Caliphornia',
			max_guests:	Math.floor((Math.random() * 10) + 1),
			no_bedrooms:	Math.floor((Math.random() * 3) + 1),
			no_bed:	Math.floor((Math.random() * 5) + 1),
			no_bath:	Math.floor((Math.random() * 5) + 1),
			price:	(Math.floor((Math.random() * 10000) + 1000)),
			currency:	'USD',
			currency_symbol:	'$ ',
			comments_and_feedback:	'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			begindate: Math.floor((Math.random() * 10) + 1),
			enddate: Math.floor((Math.random() * 10) + 10),
			guestnumbers: null,
			days_of_stay: (this.enddate - this.begindate),
		},
		{	Room_Name: 'de Finibus Bonorum et Malorum',
			address: 'Caliphornia',
			max_guests:	Math.floor((Math.random() * 10) + 1),
			no_bedrooms:	Math.floor((Math.random() * 3) + 1),
			no_bed:	Math.floor((Math.random() * 5) + 1),
			no_bath:	Math.floor((Math.random() * 5) + 1),
			price:	(Math.floor((Math.random() * 10000))),
			currency:	'USD',
			currency_symbol:	'$ ',
			comments_and_feedback:	'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			begindate: 5,
			enddate: 8,
			guestnumbers:null,
			days_of_stay: (this.enddate - this.begindate),
			currentdate: null,
		},
		]
	}
});
